package io.github.andjsrk.v4.parse

enum class ReservedWord(val isContextual: Boolean = false) {
    AS(isContextual=true),
    ASYNC,
    AWAIT,
    BREAK,
    CASE,
    CATCH,
    CLASS,
    CONSTRUCTOR(isContextual=true),
    CONTINUE,
    DEFAULT,
    ELSE,
    EXPORT,
    EXTENDS,
    FALSE,
    FINALLY,
    FOR,
    FROM(isContextual=true),
    GEN,
    GET(isContextual=true),
    IF,
    IMPORT,
    IN,
    INSTANCEOF,
    LET,
    METHOD,
    NEW,
    NULL,
    RETURN,
    SET(isContextual=true),
    STATIC,
    SUPER,
    SWITCH,
    THIS,
    THROW,
    TRUE,
    TRY,
    TYPEOF,
    VAR,
    VOID,
    WHILE,
    YIELD;

    val value = name.lowercase()
}
