package io.github.andjsrk.v4.error

enum class RangeErrorKind(override val message: String): ErrorKind {
    ARRAY_BUFFER_ALLOCATION_FAILED("Array buffer allocation failed"),
    BIGINT_DIV_ZERO("Division by zero"),
    BIGINT_TOO_BIG("Maximum BigInt size exceeded"),
    CANT_SET_OPTION_X_WHEN_Y_IS_USED("Can't set option % when % is used"),
    COLLECTION_GROW_FAILED("% maximum size exceeded"),
    EXPECTED_LOCATION("Expected letters optionally connected with underscores or hyphens for a location, got %"),
    INVALID("Invalid % : %"),
    INVALID_ARRAY_BUFFER_LENGTH("Invalid array buffer length"),
    INVALID_ARRAY_BUFFER_MAX_LENGTH("Invalid array buffer max length"),
    INVALID_ARRAY_BUFFER_RESIZE_LENGTH("%: Invalid length parameter"),
    INVALID_ARRAY_LENGTH("Invalid array length"),
    INVALID_ATOMIC_ACCESS_INDEX("Invalid atomic access index"),
    INVALID_CALENDAR("Invalid calendar specified: %"),
    INVALID_CODE_POINT("Invalid code point %"),
    INVALID_COUNT_VALUE("Invalid count value: %"),
    INVALID_DATA_VIEW_ACCESSOR_OFFSET("Offset is outside the bounds of the DataView"),
    INVALID_DATA_VIEW_LENGTH("Invalid DataView length %"),
    INVALID_HINT("Invalid hint: %"),
    INVALID_INDEX("Invalid value: not (convertible to) a safe integer"),
    INVALID_LANGUAGE_TAG("Invalid language tag: %"),
    INVALID_OFFSET("Start offset % is outside the bounds of the buffer"),
    INVALID_SHADOW_REALM_EVALUATE_SOURCE_TEXT("Invalid value used as source text"),
    INVALID_STRING_LENGTH("Invalid string length"),
    INVALID_TIME_VALUE("Invalid time value"),
    INVALID_TIME_VALUE_FOR_TEMPORAL("Invalid time value for Temporal %"),
    INVALID_TIME_ZONE("Invalid time zone specified: %"),
    INVALID_TYPED_ARRAY_ALIGNMENT("% of % should be a multiple of %"),
    INVALID_TYPED_ARRAY_INDEX("Invalid typed array index"),
    INVALID_TYPED_ARRAY_LENGTH("Invalid typed array length: %"),
    INVALID_WEAK_MAP_KEY("Invalid value used as weak map key"),
    INVALID_WEAK_SET_VALUE("Invalid value used in weak set"),
    LOCALE_MATCHER("Illegal value for localeMatcher:%"),
    MAXIMUM_FRACTION_DIGITS_NOT_EQUAL_MINIMUM_FRACTION_DIGITS("maximumFractionDigits not equal to minimumFractionDigits"),
    MUST_BE_FINITE("The number must be finite"),
    MUST_BE_POSITIVE("The number must be positive"),
    NORMALIZATION_FORM("The normalization form should be one of %"),
    NUMBER_FORMAT_RANGE("% argument must be between 0 and 100"),
    OUT_OF_MEMORY("%: Out of memory"),
    PROPERTY_VALUE_OUT_OF_RANGE("% value is out of range"),
    SHARED_ARRAY_SIZE_OUT_OF_RANGE("SharedArray length out of range (maximum of 2**14-2 allowed)"),
    STACK_OVERFLOW("Maximum call stack size exceeded"),
    STRUCT_FIELD_COUNT_OUT_OF_RANGE("Struct field count out of range (maximum of 999 allowed)"),
    TEMPLATE_STRING_OUT_OF_RANGE("Template string out of range (maximum of 2**32 allowed)"),
    TO_PRECISION_FORMAT_RANGE("toPrecision() argument must be between 1 and 100"),
    RADIX_RANGE("radix argument must be an integer between 2 and 36"),
    TYPED_ARRAY_SET_OFFSET_OUT_OF_BOUNDS("offset is out of bounds"),
    TYPED_ARRAY_SET_SOURCE_TOO_LARGE("Source is too large"),
    TYPED_ARRAY_TOO_LARGE_TO_SORT("Custom comparefn not supported for huge TypedArrays"),
    VALUE_OUT_OF_RANGE("Value % out of range for % options property %"),
    ZERO_DIGIT_NUMERIC_SEPARATOR("Numeric separator can not be used after leading 0"),
}
