package io.github.andjsrk.v4.tokenize

enum class TokenType(val staticContent: String?, val precedence: Int = 0) {
    EOS(null),
    ILLEGAL(null),
    TEMPLATE_HEAD(null),
    TEMPLATE_MIDDLE(null),
    TEMPLATE_TAIL(null),
    TEMPLATE_FULL(null),
    DOT("."),
    LEFT_BRACKET("["),
    QUESTION_DOT("?."),
    LEFT_PARENTHESIS("("),
    RIGHT_PARENTHESIS(")"),
    RIGHT_BRACKET("]"),
    LEFT_BRACE("{"),
    COLON(":"),
    ELLIPSIS("..."),
    CONDITIONAL("?", 3),
    SEMICOLON(";"),
    RIGHT_BRACE("}"),
    ARROW("=>"),
    ASSIGN("=", 2),
    ASSIGN_COALESCE("??=", 2),
    ASSIGN_OR("||=", 2),
    ASSIGN_AND("&&=", 2),
    ASSIGN_BITWISE_OR("|=", 2),
    ASSIGN_BITWISE_XOR("^=", 2),
    ASSIGN_BITWISE_AND("&=", 2),
    ASSIGN_SHL("<<=", 2),
    ASSIGN_SAR(">>=", 2),
    ASSIGN_SHR(">>>=", 2),
    ASSIGN_MULTIPLY("*=", 2),
    ASSIGN_DIVIDE("/=", 2),
    ASSIGN_MOD("%=", 2),
    ASSIGN_EXPONENTIAL("**=", 2),
    ASSIGN_PLUS("+=", 2),
    ASSIGN_MINUS("-=", 2),
    COMMA(",", 1),
    COALESCE("??", 3),
    OR("||", 4),
    AND("&&", 5),
    BITWISE_OR("|", 6),
    BITWISE_XOR("^", 7),
    BITWISE_AND("&", 8),
    SHL("<<", 11),
    SAR(">>", 11),
    SHR(">>>", 11),
    MULTIPLY("*", 13),
    DIVIDE("/", 13),
    MOD("%", 13),
    EXPONENTIAL("**", 14),
    PLUS("+", 12),
    MINUS("-", 12),
    NOT("!"),
    BITWISE_NOT("~"),
    INCREMENT("++"),
    DECREMENT("--"),
    EQ("==", 9),
    EQ_STRICT("===", 9),
    NOT_EQ("!=", 9),
    NOT_EQ_STRICT("!==", 9),
    LT("<", 10),
    GT(">", 10),
    LT_EQ("<=", 10),
    GT_EQ(">=", 10),
    NUMBER(null),
    BIGINT(null),
    STRING(null),
    PRIVATE_NAME(null),
    WHITE_SPACE(null),
    REGEXP_LITERAL(null),
    IDENTIFIER(null);
}
